const prefix = process.env.NEXT_PUBLIC_BASE_PATH || ''
export const projects = [
  {
    title: 'Lightning Goods',
    description: "Co-founded a platform that sells North American products that are inaccessible in the Chinese market and importing products to the western market. I am currenlty responsible for the full-stack development and DevOps of the platform.",
    image: prefix + '/images/lg.png',
    tags: ['Flask', 'PostgreSQL', 'Vue.js', 'AWS', 'Heroku'],
    source: '',
    visit: 'https://lightning-goods.com/en/',
    id: 0,
  },
  {
    title: "Optimal Biomaterial Compositions with ML",
    description: "Part of a research lab designing ML models that learn how to predict the outcomes of Agent-Based models (ABM) and interpolate outcomes between ABM time steps to ultimately create ML models that can find the optimal biomaterial compositions for vocal folds repair.",
    image: prefix + '/images/COMBINE.png',
    tags: ['Machine Learning', 'Sklean', 'XGBoost'],
    source: '',
    visit: 'https://www.ece.mcgill.ca/~aemad2/',
    id: 1,
  },
  {
    title: "Biofeedback for Surgical Practice",
    description: "Built a lightweight biofeedback application that uses video camera feed to detect and alert users of non-ergonomic postures to avoid long-term pain. Originally made for the medical field, the appplication can also be used in any environment to prevent strain injuries.",
    image: prefix + '/images/posture.png',
    tags: ['Computer Vision', 'Data Analysis', 'OpenCV'],
    source: 'https://github.com/PhilippeShi/posture-biofeedback',
    id: 2,
  },
  {
    title: 'Medical Image Analysis and Deep Learning',
    description: 'I participated in a hackathon that is about image analysis in the medical field. The goal was to implement semantic segmentation of multi-layered brain CT scans to isolate Alpha Tau seeds (symptoms of brain cancer). The project received a "Rising Star" honourable mention.',
    image: prefix + '/images/hackathon.png',
    tags: ['Jupyter', 'Keras'],
    source: '',
    visit: 'https://devpost.com/software/we-have-an-idea',
    id: 3,
  },
  {
    title: 'Study Buddy Matching Application',
    description: "A full-stack web application that allows McGill students to find study buddies based on their courses, freetime, and interests. I was the scrum master of a team of 8.",
    image: prefix + '/images/studybuddy.png',
    tags: ['Flask', 'PostgreSQL', 'Vue.js', 'Gherkin'],
    source: '',
    visit: '',
    na: 'https://w22-428-studybuddy-front-test.herokuapp.com/',
    id: 4,
  },
  {
    title: 'Online Library System',
    description: "This is an application for a library system made from the ground up in a team of six developers. Both the database and the frontend of this application are deployed on Heroku.",
    image: prefix + '/images/library.gif',
    tags: [, 'Spring', 'PostgreSQL', 'Vue.js'],
    // source: 'https://drive.google.com/drive/folders/1fVlXdNt0x6iw_aFhS3PptrBGdrpdDPFC?usp=sharing',
    na: 'https://onlinelibrarysystem-frontend.herokuapp.com/#/',
    id: 5,
  },
  // {
  //   title: 'Action Rep Counter',
  //   description: "Created an application that counts the repetitions of any action/exercise that has two distinct positions using a simple ML model, which applies linear kernel function to perform the classification of images.",
  //   image: prefix + '/images/counter.gif',
  //   tags: ['OpenCV', 'scikit-learn'],
  //   source: 'https://github.com/PhilippeShi/counter',
  //   visit: '',
  //   id: 1,
  // },
  // {
  //   title: 'Auto Web Navigation and Scraping',
  //   description: "Scripts used to automate tasks that I would do every day. The demo shown is an example of one of them. It retrieves the different colors of an item available to buy online, and the number of seats available for specific sections of a course from McGill's website.",
  //   image: prefix +'/images/selenium_short.gif',
  //   tags: ['Selenium'],
  //   source: 'https://github.com/PhilippeShi/Auto-web-navigation',
  //   visit: '',
  //   id: 2,
  // },
  // {
  //   title: 'Object Detection',
  //   description: "A simple object detection script implemented with a pre-trained model made by Darknet.",
  //   image: prefix +'/images/opencv.png',
  //   tags: [OpenCV','YOLO v3'],
  //   source: 'https://github.com/PhilippeShi/Object-Detection',
  //   visit: '',
  //   id: 4,
  // },
  {
    title: 'Sudoku Solver',
    description: "Wrote an algorithm that can solve a sudoku puzzle of any grid size. Optimized excecution time by fetching and sloving cells that have the least number of possibilities. There is also an option to include the Knight, King, and/or Queen rule to add more contraints to the possible solutions.",
    image: prefix +'/images/sudoku.png',
    tags: [],
    source: 'https://github.com/PhilippeShi/Sudoku-Solver',
    visit: '',
    id: 6,
  },
  {
    title: 'Pong Game',
    description: "Pong game player versus computer. The ball's behavior, as well as the difficulty, can be ajusted according to the player's preferences. In this demo, real-life physics are used for the ball's motion and the ball's speed increases when hitting a paddle.",
    image: prefix + '/images/pong.gif',
    tags: [],
    source: 'https://drive.google.com/drive/folders/1ZP9YyHURgd9VEp4Zxyy9el5RCKfWEmI4?usp=sharing',
    visit: '',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Wrote my first "Hello World!" script and learned about the basics of programing.', },
  { year: 2020, text: 'Enrolled in the software engineering program at McGill. Got to learn about the core principles of software development.', },
  { year: 2021, text: 'Introduced to ML and learned how to build and deploy web applications from the ground-up.', },
  { year: 2022, text: "Co-founded my first startup and gained hands-on experience in ML through a research project." },
  { year: 2023, text: "I'm excited too see what I can accomplish this year!! 😀" },
];
